# Generated by Django 5.1.4 on 2026-05-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('restart', 'Restart server'), ('backup_world', 'Backup world'), ('backup_full', 'Backup full'), ('rcon', 'RCON command')], max_length=20)),
                ('cron', models.CharField(help_text='Standard 5-field cron', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never_run', 'Never run'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='never_run', max_length=20)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['-enabled', 'name'],
            },
        ),
    ]
