# Generated by Django 5.1.4 on 2026-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_percent', models.FloatField(null=True)),
                ('memory_used', models.BigIntegerField(null=True)),
                ('memory_limit', models.BigIntegerField(null=True)),
                ('players_online', models.IntegerField(null=True)),
                ('players_max', models.IntegerField(null=True)),
                ('tps_1m', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'perf_samples',
                'ordering': ['t'],
                'indexes': [models.Index(fields=['-t'], name='perf_t_desc_idx')],
            },
        ),
    ]
