# Generated by Django 5.1.4 on 2026-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchdogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('threshold_seconds', models.PositiveIntegerField(default=120, help_text='How long Health.Status must be `unhealthy` before we trigger a restart.')),
                ('max_restarts_per_hour', models.PositiveIntegerField(default=3, help_text='Hard cap to prevent boot-loops from hammering the host.')),
                ('last_restart_at', models.DateTimeField(blank=True, null=True)),
                ('total_restarts', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'server_watchdog',
            },
        ),
    ]
