# Generated by Django 5.1.4 on 2026-05-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('project_id', models.CharField(db_index=True, max_length=128)),
                ('project_slug', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('icon_url', models.URLField(blank=True, default='')),
                ('project_url', models.URLField(blank=True, default='')),
                ('version_id', models.CharField(max_length=128)),
                ('version_number', models.CharField(blank=True, default='', max_length=64)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('hash_algo', models.CharField(blank=True, default='', max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('mod', 'Mod'), ('plugin', 'Plugin')], max_length=10)),
                ('loader', models.CharField(blank=True, default='', max_length=32)),
                ('mc_version', models.CharField(blank=True, default='', max_length=32)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mods_installed',
                'ordering': ['-installed_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'project_id'), name='uniq_provider_project')],
            },
        ),
    ]
