# Generated by Django 5.1.4 on 2026-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('direct', 'Direct (port-forward)'), ('playit_guided', 'Playit (guided)'), ('playit_managed', 'Playit (managed)')], default='direct', max_length=32)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=255)),
                ('playit_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('playit_agent_key', models.TextField(blank=True, default='')),
                ('public_ip_override', models.CharField(blank=True, default='', max_length=45)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'network_profile',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('host_port', models.PositiveIntegerField()),
                ('container_port', models.PositiveIntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=4)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'network_allocations',
                'ordering': ['host_port'],
                'constraints': [models.UniqueConstraint(fields=('host_port', 'protocol'), name='uniq_alloc_host_port_proto')],
            },
        ),
    ]
