# Generated by Django 5.1.4 on 2026-05-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('s3', 'S3-compatible')], default='s3', max_length=20)),
                ('endpoint_url', models.CharField(blank=True, default='', help_text='e.g. https://s3.us-west-001.backblazeb2.com — leave blank for AWS S3', max_length=255)),
                ('bucket', models.CharField(max_length=255)),
                ('prefix', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='us-east-1', max_length=64)),
                ('access_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('auto_upload', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backup_destinations',
                'ordering': ['-enabled', 'name'],
            },
        ),
        migrations.AddField(
            model_name='backup',
            name='remote_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backup',
            name='remote_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='backup',
            name='remote_status',
            field=models.CharField(choices=[('none', 'Local only'), ('pending', 'Pending upload'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Upload failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='backup',
            name='remote_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='backups.backupdestination'),
        ),
    ]
