# Generated by Django 5.1.4 on 2026-05-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_backupdestination_backup_remote_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='restore_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='backup',
            name='restore_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Restoring'), ('done', 'Restored'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='backup',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
